#!/usr/bin/env python

import socket
import sys
import json

HOST = '0.0.0.0'
PORT = sys.argv[1]

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, int(PORT)))
    s.listen()
    while True:
        conn, addr = s.accept()
        with conn:
            data = conn.recv(1024)
            request = json.loads(data)            
            response = {
                'status': 200,
                'header': {},
                'body': "hello " + request['Params']['name'][0] + " Python listener"
            }
            conn.sendall(str.encode(json.dumps(response)+"\n", 'utf-8' ))